### PR TITLE
Update to Alpine 3.8

### PR DESCRIPTION
**Pull request by ckotte**
### Description of the Change

just an upgrade from Alpine 3.7 to 3.8

### Verification Process

re-deployed Jira container

### Applicable Issues

no issues so far

### CODE REVIEW

**Comment by jhult** [comment]
FWIW,

This did build for me. However, I have not yet tested running it.

**Comment by ckotte** [comment]
It works fine on my side. I'm running Jira with Alpine 3.8 for two weeks now. However, I don't use it that much...

**Comment by blacklabelops** [comment]
Will have to wait until i can check myself

**Comment by blacklabelops** [comment]
Thanks for upgrading and testing.

**Pull request merged**
